name: Use Central Docker Action

on:
  push:
    branches:
      - main 

jobs:
  call-central-action:
    uses: devops-ktm/centralized-docker-action/.github/workflows/docker-build.yml@main
    with:
      image_name: my-rails-app
